title: "Mahhin Shahzad"

logo: "/images/Profileimg.jpg?raw=true"

description: >
  <p align="center">
  <a href="pdf/Mahhin Resume .pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mahhin-shahzad-813451218/">LinkedIn</a> |
  <a href="https://github.com/Mahhin1010">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing a Bachelor's degree in Computer Science from FUUAST Islamabad.
  Currently, I am looking for a position as a Junior Data Analyst. I have prior experience in related analytical tasks.
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-145578661-1
