title: "Mahhin Shahzad"

logo: "/images/Profileimg.jpg?raw=true"

description: >
  <p align="center">
  <a href="pdf/Mahhin Resume .pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mahhin-shahzad-813451218/">LinkedIn</a> |
  <a href="https://github.com/Mahhin1010">GitHub</a>
  </p>
  
  <p align="justify">
 I am one year away from completing my Bachelor's degree in Computer Science from FUUAST Islamabad.
  Currently working as a BI Developer at Proforecast, where I'm leading the BI suite to the next level.
  </p>

theme: jekyll-theme-minimal
google_analytics: G-ETBVX0Z22J