title: <p align="center"> Mahhin Shahzad </p>

logo: "/images/Profileimg.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/Mahhin Resume .pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mahhin-shahzad-813451218/">LinkedIn</a> |
  <a href="https://github.com/Mahhin1010">GitHub</a>
  #https://github.com/Mahhin1010
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, University of Rochester.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
