/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#356382",
        "primary-dim": "#285775",
        "primary-container": "#cae6ff",
        "primary-fixed": "#cae6ff",
        "primary-fixed-dim": "#addafe",
        "on-primary": "#f3f8ff",
        "on-primary-container": "#275675",
        "on-primary-fixed": "#0e4361",
        "on-primary-fixed-variant": "#32607f",
        "secondary": "#466370",
        "secondary-dim": "#3a5764",
        "secondary-container": "#c9e7f7",
        "secondary-fixed": "#c9e7f7",
        "secondary-fixed-dim": "#bbd9e9",
        "on-secondary": "#f3faff",
        "on-secondary-container": "#395663",
        "on-secondary-fixed": "#264350",
        "on-secondary-fixed-variant": "#435f6d",
        "tertiary": "#4f6176",
        "tertiary-dim": "#43556a",
        "tertiary-container": "#d1e4fe",
        "tertiary-fixed": "#d1e4fe",
        "tertiary-fixed-dim": "#c3d6ef",
        "on-tertiary": "#f7f9ff",
        "on-tertiary-container": "#415368",
        "on-tertiary-fixed": "#2f4155",
        "on-tertiary-fixed-variant": "#4b5d72",
        "surface": "#f8fafb",
        "surface-bright": "#f8fafb",
        "surface-dim": "#cfdce0",
        "surface-container": "#e8eff1",
        "surface-container-low": "#f0f4f6",
        "surface-container-high": "#e1eaec",
        "surface-container-highest": "#d9e4e8",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d9e4e8",
        "surface-tint": "#356382",
        "on-surface": "#2a3437",
        "on-surface-variant": "#566164",
        "on-background": "#2a3437",
        "background": "#f8fafb",
        "outline": "#727d80",
        "outline-variant": "#a9b4b7",
        "inverse-surface": "#0b0f10",
        "inverse-on-surface": "#9a9d9e",
        "inverse-primary": "#aad7fb",
        "error": "#9f403d",
        "error-dim": "#4e0309",
        "error-container": "#fe8983",
        "on-error": "#fff7f6",
        "on-error-container": "#752121",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
